server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: 123456
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: "*"