server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_microservice?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
